In [ ]:
import numpy as np

Q1 Let x = np.arange(4, dtype=np.int64). Create an array of ones with the same shape and type as X.

In [ ]:
x = np.arange(4, dtype=np.int64)
y = np.ones(np.shape(x), dtype=np.int64)
print(x,y)

[0 1 2 3] [1 1 1 1]


Q2 Let X = np.array([[1, 2], [3, 4]]). Convert it into a matrix.

In [ ]:
X = np.array([[1, 2], [3, 4]])
X= np.matrix(X)
print(X)

[[1 2]
 [3 4]]


Q3 Create a 1-D array of 50 evenly spaced elements between 3. and 10., inclusive.

In [ ]:
X=np.arange(3,10,0.14,dtype=float)
print(X)

[3.   3.14 3.28 3.42 3.56 3.7  3.84 3.98 4.12 4.26 4.4  4.54 4.68 4.82
 4.96 5.1  5.24 5.38 5.52 5.66 5.8  5.94 6.08 6.22 6.36 6.5  6.64 6.78
 6.92 7.06 7.2  7.34 7.48 7.62 7.76 7.9  8.04 8.18 8.32 8.46 8.6  8.74
 8.88 9.02 9.16 9.3  9.44 9.58 9.72 9.86]


Q4 Let x be array [[1, 2, 3], [4, 5, 6]]. Convert it to [1 4 2 5 3 6].

In [ ]:
X= ([[1,2,3],[4,5,6]])
X=np.dstack(X).ravel()
print(X)

[1 4 2 5 3 6]


Q5 Let x be an array [1, 2, 3, ..., 9]. Split x into 3 arrays, each of which has 4, 2, and 3 elements in the original order.

In [ ]:
x=np.arange(1,10,1,dtype=int).reshape(3,3)
x=(np.hsplit(x,3))
print(x)

[array([[1],
       [4],
       [7]]), array([[2],
       [5],
       [8]]), array([[3],
       [6],
       [9]])]


 Q6 Compute the inverse and primary diagnol sum of x=[[1,2],[3,4]]

In [ ]:
x=[[1,2],[3,4]]
s=np.trace(x)
print(s)
y = np.linalg.inv(x)
print(y)

5
[[-2.   1. ]
 [ 1.5 -0.5]]


Q7 Sort x along the second axis. x = [[1,4],[3,1]]

In [ ]:
x=np.array([[1,4], [3,1]])
x.sort(axis=1)
print(x)


[[1 4]
 [1 3]]


Q8 Get the indices that would sort x(as above) along the second axis.

In [ ]:
x=np.array([[1,4], [3,1]])
print(np.argsort(x,axis=1))

[[0 1]
 [1 0]]


Initiate x as a 2x5 array with random values from 0 to 10(not inclusive).Get the maximum and minimum values and their indices of x along the second axis.

In [ ]:
import random
x=np.array(random.choices(range(0,10),k=10)).reshape(2,5)
print(x)
xmin,xmax=x.min(),x.max()
print(np.argmax(x),np.argmin(x))


[[5 2 5 4 2]
 [2 4 8 6 2]]
7 1


Run the following load command to get the 2-Dim iris dataset. Do the following operations on it.

In [ ]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])

Drop rows that contain a missing value. 

In [ ]:
print(iris_2d[~np.isnan(iris_2d).any(axis=1), :])

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.1 1.5 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.  1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [5.  3.3 1.4 0.2]
 [7.  3.2 4.7 1.4]
 [6.4 3.2 4.5 1.5]
 [6.9 3.1 4.

Find the correlation between first two columns.

In [ ]:
np.corrcoef(iris_2d[:, 0], iris_2d[:, 1])[0,1]

-0.10936924995064937

Find the mean,median and standard deviation of column 3.

In [ ]:
print(np.average(iris_2d[2]),np.median(iris_2d[2]),round(np.std(iris_2d[2]),2))

2.35 2.25 1.73


Create a new column for volume in iris_2d, where volume is (pi x petallength x sepal_length^2)/3

In [ ]:
volume=(np.pi*iris_2d[:,2]*iris_2d[:,0]*iris_2d[:,0]/3)
volume = volume[:, np.newaxis]
iris_2d=np.hstack([iris_2d, volume])
print(iris_2d)

[[  5.1          3.5          1.4          0.2         38.13265163]
 [  4.9          3.           1.4          0.2         35.20049849]
 [  4.7          3.2          1.3          0.2         30.07237208]
 [  4.6          3.1          1.5          0.2         33.23805027]
 [  5.           3.6          1.4          0.2         36.65191429]
 [  5.4          3.9          1.7          0.4         51.91167701]
 [  4.6          3.4          1.4          0.3         31.02218026]
 [  5.           3.4          1.5          0.2         39.26990817]
 [  4.4          2.9          1.4          0.2         28.38324243]
 [  4.9          3.1          1.5          0.1         37.71481981]
 [  5.4          3.7          1.5          0.2         45.80442089]
 [  4.8          3.4          1.6          0.2         38.60389053]
 [  4.8          3.           1.4          0.1         33.77840421]
 [  4.3          3.           1.1          0.1         21.29895099]
 [  5.8          4.           1.2          0.2  

Run the following loaad command and solve the following questions

In [ ]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')
names = ('sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'species')

Find the count of unique species.

In [ ]:
print(np.unique(np.array(iris[:,4]),return_counts=True))

(array([b'Iris-setosa', b'Iris-versicolor', b'Iris-virginica'],
      dtype=object), array([50, 50, 50]))


Bin the petal length (3rd) column of iris_2d to form a text array, such that if petal length is:
Less than 3 –> ‘small’
3-5 –> ‘medium’
‘>=5 –> ‘large’

In [ ]:
bin = np.digitize(iris[:, 2].astype('float'), [0, 3, 5])
label_map = {1: 'small', 2: 'medium', 3: 'large'}
cat = [label_map[x] for x in bin]
print(cat)

['small', 'small', 'small', 'small', 'small', 'small', 'small', 'small', 'small', 'small', 'small', 'small', 'small', 'small', 'small', 'small', 'small', 'small', 'small', 'small', 'small', 'small', 'small', 'small', 'small', 'small', 'small', 'small', 'small', 'small', 'small', 'small', 'small', 'small', 'small', 'small', 'small', 'small', 'small', 'small', 'small', 'small', 'small', 'small', 'small', 'small', 'small', 'small', 'small', 'small', 'medium', 'medium', 'medium', 'medium', 'medium', 'medium', 'medium', 'medium', 'medium', 'medium', 'medium', 'medium', 'medium', 'medium', 'medium', 'medium', 'medium', 'medium', 'medium', 'medium', 'medium', 'medium', 'medium', 'medium', 'medium', 'medium', 'medium', 'large', 'medium', 'medium', 'medium', 'medium', 'medium', 'large', 'medium', 'medium', 'medium', 'medium', 'medium', 'medium', 'medium', 'medium', 'medium', 'medium', 'medium', 'medium', 'medium', 'medium', 'medium', 'medium', 'large', 'large', 'large', 'large', 'large', 'large

Find the most frequent value of petal length (3rd column) in iris dataset

In [ ]:
unique, counts = np.unique(np.array(iris[:,2]), return_counts=True)
print(unique[counts.argmax()])

b'1.5'
